version: '3'
services:
  app:
    container_name: vh-manager
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    networks:
      - vhmanager  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db  
    networks:
      - vhmanager   
volumes:
  mongodb:
    driver: local
networks:
  vhmanager:
    driver: bridge
